/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrameDuAn;

import DAO.ChuyenDeDAO;
import DAO.KhoaHocDAO;
import FileHelper.DateHelper;
import FileHelper.DialogHelper;
import FileHelper.ShareHelper;
import Model.ChuyenDe;
import Model.KhoaHoc;
import java.awt.HeadlessException;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author DELL
 */
public class KhoaHocJFrame extends javax.swing.JFrame {

    /**
     * Creates new form QuanLiKhoaHocJFrame
     */
    public KhoaHocJFrame() {
        initComponents();
           
this.fillComboBox();
this.load();
this.clear();
this.setStatus(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtNgayKG = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtHocPhi = new javax.swing.JTextField();
        txtThoiLuong = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtNgayTao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        bntThem = new javax.swing.JButton();
        bntSua = new javax.swing.JButton();
        bntXoa = new javax.swing.JButton();
        bntMoi = new javax.swing.JButton();
        bntDau = new javax.swing.JButton();
        bntLui = new javax.swing.JButton();
        bntToi = new javax.swing.JButton();
        bntCuoi = new javax.swing.JButton();
        bntSudents = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGirdView = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 400));

        jLabel2.setText("Chuyên đề");

        jLabel3.setText("Ngày khai giảng");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lập trình java cơ bản", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Học phí");

        jLabel5.setText("Thời lượng(giờ)");

        txtThoiLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThoiLuongActionPerformed(evt);
            }
        });

        jLabel6.setText("Người tạo");

        jLabel7.setText("Ngày tạo");

        txtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNVActionPerformed(evt);
            }
        });

        txtNgayTao.setEnabled(false);

        jLabel8.setText("Ghi chú");

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane1.setViewportView(txtGhiChu);

        bntThem.setText("Thêm");
        bntThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntThemActionPerformed(evt);
            }
        });

        bntSua.setText("Sửa");
        bntSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSuaActionPerformed(evt);
            }
        });

        bntXoa.setText("Xóa");
        bntXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntXoaActionPerformed(evt);
            }
        });

        bntMoi.setText("Mới");
        bntMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMoiActionPerformed(evt);
            }
        });

        bntDau.setText("|<<");
        bntDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDauActionPerformed(evt);
            }
        });

        bntLui.setText("<<");
        bntLui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntLuiActionPerformed(evt);
            }
        });

        bntToi.setText(">>");
        bntToi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntToiActionPerformed(evt);
            }
        });

        bntCuoi.setText(">>|");
        bntCuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCuoiActionPerformed(evt);
            }
        });

        bntSudents.setText("Học viên");
        bntSudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSudentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox1, 0, 287, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(txtHocPhi)
                            .addComponent(jLabel6)
                            .addComponent(txtMaNV))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgayKG)
                            .addComponent(txtThoiLuong)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(0, 364, Short.MAX_VALUE))
                            .addComponent(txtNgayTao)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(bntThem)
                .addGap(18, 18, 18)
                .addComponent(bntSua)
                .addGap(18, 18, 18)
                .addComponent(bntXoa)
                .addGap(18, 18, 18)
                .addComponent(bntMoi)
                .addGap(18, 18, 18)
                .addComponent(bntSudents)
                .addGap(34, 34, 34)
                .addComponent(bntDau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntLui)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bntToi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntCuoi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNgayKG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHocPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThoiLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntThem)
                    .addComponent(bntSua)
                    .addComponent(bntXoa)
                    .addComponent(bntMoi)
                    .addComponent(bntDau)
                    .addComponent(bntLui)
                    .addComponent(bntToi)
                    .addComponent(bntCuoi)
                    .addComponent(bntSudents))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab1.addTab("CẬP NHẬT", jPanel1);

        tblGirdView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "MÃ KH", "CHUYÊN ĐỀ", "THỜI LƯỢNG", "HỌC PHÍ", "NGÀY KHAI GIẢNG", "TẠO BỞI", "NGÀY TẠO"
            }
        ));
        tblGirdView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGirdViewMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblGirdView);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab1.addTab("DANH SÁCH", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(tab1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblGirdViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGirdViewMouseClicked
        if(evt.getClickCount() == 1){
this.index = tblGirdView.rowAtPoint(evt.getPoint());
        if (this.index >= 0) {
this.edit();
tab1.setSelectedIndex(0);
}
}
        // TODO add your handling code here:
    }//GEN-LAST:event_tblGirdViewMouseClicked

    private void bntThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntThemActionPerformed
insert();        // TODO add your handling code here:
    }//GEN-LAST:event_bntThemActionPerformed

    private void bntSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSuaActionPerformed
        update();// TODO add your handling code here:
    }//GEN-LAST:event_bntSuaActionPerformed

    private void bntXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntXoaActionPerformed
        delete();// TODO add your handling code here:
    }//GEN-LAST:event_bntXoaActionPerformed

    private void bntMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMoiActionPerformed
        clear();// TODO add your handling code here:
    }//GEN-LAST:event_bntMoiActionPerformed

    private void bntDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDauActionPerformed
        this.index = 0;
this.edit();// TODO add your handling code here:
    }//GEN-LAST:event_bntDauActionPerformed

    private void bntLuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLuiActionPerformed
       this.index--;
this.edit(); // TODO add your handling code here:
    }//GEN-LAST:event_bntLuiActionPerformed

    private void bntToiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntToiActionPerformed
        this.index++;
this.edit();// TODO add your handling code here:
    }//GEN-LAST:event_bntToiActionPerformed

    private void bntCuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCuoiActionPerformed
       this.index = tblGirdView.getRowCount() - 1;
this.edit(); // TODO add your handling code here:
    }//GEN-LAST:event_bntCuoiActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
//        selectComboBox();
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void bntSudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSudentsActionPerformed
        this.openHocVien();        // TODO add your handling code here:
    }//GEN-LAST:event_bntSudentsActionPerformed

    private void txtThoiLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThoiLuongActionPerformed
        
    selectComboBox();  // TODO add your handling code here:
    }//GEN-LAST:event_txtThoiLuongActionPerformed

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhoaHocJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhoaHocJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhoaHocJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhoaHocJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhoaHocJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCuoi;
    private javax.swing.JButton bntDau;
    private javax.swing.JButton bntLui;
    private javax.swing.JButton bntMoi;
    private javax.swing.JButton bntSua;
    private javax.swing.JButton bntSudents;
    private javax.swing.JButton bntThem;
    private javax.swing.JButton bntToi;
    private javax.swing.JButton bntXoa;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane tab1;
    private javax.swing.JTable tblGirdView;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtHocPhi;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtNgayKG;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtThoiLuong;
    // End of variables declaration//GEN-END:variables

int index = 0;
KhoaHocDAO dao = new KhoaHocDAO();
ChuyenDeDAO cddao = new ChuyenDeDAO();
void init() {
setIconImage(ShareHelper.APP_ICON);
setLocationRelativeTo(null);
}
void load() {
DefaultTableModel model = (DefaultTableModel) tblGirdView.getModel();
model.setRowCount(0);
try {
List<KhoaHoc> list = dao.select();
for (KhoaHoc kh : list) {
Object[] row = {
kh.getMaKH(),
kh.getMaCD(),
kh.getThoiLuong(),
kh.getHocPhi(),
DateHelper.toString(kh.getNgayKG()),
kh.getMaNV(),
DateHelper.toString(kh.getNgayTao())
};
model.addRow(row);
}
}
catch (Exception e) {
DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
}
}
void insert(){
KhoaHoc model = getModel();
model.setNgayTao(new Date());
try {
dao.insert(model);
this.load();
this.clear();
DialogHelper.alert(this, "Thêm mới thành công!");
}
catch (HeadlessException e) {
DialogHelper.alert(this, "Thêm mới thất bại!");
}
}
void update(){
KhoaHoc model = getModel();
try {
dao.update(model);
this.load();
DialogHelper.alert(this, "Cập nhật thành công!");
}
catch (Exception e) {
DialogHelper.alert(this, "Cập nhật thất bại!");
}
}
void delete(){
if(DialogHelper.confirm(this, "Bạn thực sự muốn xóa khóa học này?")){
Integer makh = Integer.valueOf(jComboBox1.getToolTipText());
try {
dao.delete(makh);
this.load();
this.clear();
DialogHelper.alert(this, "Xóa thành công!");
}
catch (Exception e) {
DialogHelper.alert(this, "Xóa thất bại!");
}
}
}
void clear(){
KhoaHoc model = new KhoaHoc();
ChuyenDe chuyenDe = (ChuyenDe) jComboBox1.getSelectedItem();
model.setMaCD(chuyenDe.getMaCD());
model.setMaNV(ShareHelper.USER.getMaNV());
model.setNgayKG(DateHelper.add(30));
model.setNgayTao(DateHelper.now());
this.setModel(model);
}
void edit() {
try {
Integer makh = (Integer) tblGirdView.getValueAt(this.index, 0);
KhoaHoc model = dao.findById(makh);
if(model != null){
this.setModel(model);
this.setStatus(false);
}
}
catch (Exception e) {
DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
}
}
void setModel(KhoaHoc model){
jComboBox1.setToolTipText(String.valueOf(model.getMaKH()));
jComboBox1.setSelectedItem(cddao.findById(model.getMaCD()));
txtNgayKG.setText(DateHelper.toString(model.getNgayKG()));
txtHocPhi.setText(String.valueOf(model.getHocPhi()));
txtThoiLuong.setText(String.valueOf(model.getThoiLuong()));
// txtMaNV.setText(model.getMaNV());
txtNgayTao.setText(DateHelper.toString(model.getNgayTao()));
txtGhiChu.setText(model.getGhiChu());
}
KhoaHoc getModel(){
KhoaHoc model = new KhoaHoc();
ChuyenDe chuyenDe = (ChuyenDe) jComboBox1.getSelectedItem();
model.setMaCD(chuyenDe.getMaCD());
model.setNgayKG(DateHelper.toDate(txtNgayKG.getText()));
model.setHocPhi(Double.valueOf(txtHocPhi.getText()));
model.setThoiLuong(Integer.valueOf(txtThoiLuong.getText()));
model.setGhiChu(txtGhiChu.getText());
model.setMaNV(ShareHelper.USER.getMaNV());
model.setNgayTao(DateHelper.toDate(txtNgayTao.getText()));
model.setMaKH(Integer.valueOf(jComboBox1.getToolTipText()));
return model;
}
void setStatus(boolean insertable){
bntThem.setEnabled(insertable);
bntSua.setEnabled(!insertable);
bntXoa.setEnabled(!insertable);
boolean first = this.index > 0;
boolean last = this.index < tblGirdView.getRowCount() - 1;
bntDau.setEnabled(!insertable && first);
bntLui.setEnabled(!insertable && first);
bntCuoi.setEnabled(!insertable && last);
bntToi.setEnabled(!insertable && last);
bntSudents.setVisible(!insertable);
}
void selectComboBox(){
ChuyenDe chuyenDe = (ChuyenDe) jComboBox1.getSelectedItem();
txtThoiLuong.setText(String.valueOf(chuyenDe.getThoiLuong()));
txtHocPhi.setText(String.valueOf(chuyenDe.getHocPhi()));
}
void openHocVien() {
Integer id = Integer.valueOf(jComboBox1.getToolTipText());
new HocVienJFrame(id).setVisible(true);
}
void fillComboBox(){
DefaultComboBoxModel model = (DefaultComboBoxModel) jComboBox1.getModel();
model.removeAllElements();
try {
List<ChuyenDe> list = cddao.select();
for(ChuyenDe cd : list){
model.addElement(cd);
}
}
catch (Exception e) {
DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
}
}}
